name: Orlen Price Scraper

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    # Add this section here:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install requests

      - name: Execute Scraper
        run: python history.py

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Orlen_Prices/*.pdf
          if git diff --staged --quiet; then
            echo "No new PDF found today."
          else
            git commit -m "Auto-add price protocol"
            git push
          fi
